apiVersion: v1
kind: Service
metadata:
  name: blue-green
spec:
  type: ClusterIP
  ports:
    - name: http-frontend
      port: 3000
      targetPort: 3000
    - name: http-backend
      port: 5000
      targetPort: 5000
  selector:
    component: blue-green