apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: ingress-rt
  namespace: websocket
spec:
  hosts:
    - 'apps.${DOMAIN_NAME}'
  virtualGateways:
    - name: ingress-gw
      namespace: websocket
  workloadSelectors: []
  http:
    - name: blue-green-websocket
      matchers:
        - uri:
            prefix: /websocket/blue
      forwardTo:
        destinations:
          - ref:
              name: blue-green
              namespace: websocket
            port:
              number: 5000
    - name: blue-green-backend
      matchers:
        - uri:
            prefix: /backend
      forwardTo:
        pathRewrite: /
        destinations:
          - ref:
              name: blue-green
              namespace: websocket
            port:
              number: 5000
    - name: blue-green-frontend
      matchers:
        - uri:
            prefix: /
      forwardTo:
        destinations:
          - ref:
              name: blue-green
              namespace: websocket
            port:
              number: 3000