apiVersion: networking.gloo.solo.io/v2
kind: VirtualGateway
metadata:
  name: ingress-gw
  namespace: apps
spec:
  workloads:
    - selector:
        labels:
          istio: ingressgateway
        namespace: istio-ingress
  listeners:
    - http: {}
      port:
        number: 80
      allowedRouteTables:
        - host: apps.${DOMAIN_NAME}
          selector:
            name: ingress-rt