apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ingress-tls-cert
  namespace: istio-ingress
spec:
  secretName: ingress-tls
  commonName: apps.$DOMAIN_NAME
  dnsNames:
    - apps.$DOMAIN_NAME
  issuerRef:
    name: global-cert-issuer
    kind: ClusterIssuer