apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: validate-claim-policy
  namespace: apps
spec:
  applyToRoutes:
    - route:
        labels:
          enableClaimValidation: "true"
  config:
    server:
      name: ext-auth-server
      namespace: apps
      cluster: ${CLUSTER_NAME}
    glooAuth:
      configs:
        - opaAuth:  
            modules:
              - name: allow-only-solo-org
                namespace: apps
            query: "data.test.allow == true"