apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: sock-shop-routing
  namespace: apps
spec:
  hosts:
    - 'apps.${DOMAIN_NAME}'
  virtualGateways:
    - name: sock-shop-gw
      namespace: apps
  http:
    - name: front-end
      matchers:
        - uri:
            prefix: /
      forwardTo:
        destinations:
          - ref:
              name: front-end
              namespace: apps
            port:
              number: 80